title = Marque
description = Built with Marque
layout = sidebar
theme = comté
width = 82

# Marque config
#
# layout options:
#   topnav    -> top navigation layout
#   sidebar   -> mdbook-like left sidebar layout
#
# theme options (built-in):
#   comté, rustique, pycorino, gouda, javarti, elmental, mida

