'use strict';

const DEFAULT_PALETTE = {
  primary:               '#c85a2a',
  secondary:             '#2a5ac8',
  tertiary:               '#2ac852',
  background:            '#f7f5f0',
  surface:               '#ffffff',
  'surface-alt':         '#eeece7',
  text:                  '#1a1916',
  muted:                 '#6b6860',
  border:                'rgba(0,0,0,0.09)',
  'nav-bg':              'var(--mq-surface)',
  'nav-text':            'var(--mq-text)',
  'nav-border':          'var(--mq-border)',
  'nav-active-bg':       'color-mix(in srgb, var(--mq-primary) 10%, transparent)',
  'nav-active-text':     'var(--mq-text)',
  'code-bg':             '#1e1c18',
  'code-text':           '#e8e4dc',
  'code-border':         '#352c23',
  'code-head-bg':        'var(--mq-code-bg)',
  'code-head-text':      'var(--mq-code-text)',
  'card-bg':             'var(--mq-surface)',
  'card-border':         'var(--mq-border)',
  'card-shadow':         'none',
  'card-radius':         'calc(var(--mq-radius) + 2px)',
  'callout-info-bg':     '#eef3fb',
  'callout-info-border': '#2a5ac8',
  'callout-info-text':   '#1a3060',
  'callout-warn-bg':     '#fdf5e8',
  'callout-warn-border': '#c87a2a',
  'callout-warn-text':   '#5a3510',
  'callout-danger-bg':   '#fbeaea',
  'callout-danger-border':'#c82a2a',
  'callout-danger-text': '#5a1010',
  'callout-ok-bg':       '#eaf4ee',
  'callout-ok-border':   '#2ac852',
  'callout-ok-text':     '#0e4020',
  radius:                '8px',
  'max-width':           '860px',
  'font-sans':           "'DM Sans', system-ui, sans-serif",
  'font-serif':          "'Fraunces', Georgia, serif",
  'font-mono':           "'IBM Plex Mono', monospace",
};

/**
 * Parse a `@mqs-palette { key: value; }` block body into an object.
 * Supports the short aliases: bg → background, accent → primary, accent2 → secondary.
 * Throws on unknown keys.
 */
function parsePaletteBlock(block, sourceFile) {
  const values  = {};
  const cleaned = String(block || '')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/(^|\n)\s*\/\/.*(?=\n|$)/g, '$1');

  const pairRe = /([a-z][a-z0-9-]*)\s*:\s*([^;]+);?/gi;
  let match;
  while ((match = pairRe.exec(cleaned))) {
    const key   = match[1].toLowerCase();
    const value = match[2].trim();
    if (!value) continue;
    if (key === 'bg')      { values.background = value; continue; }
    if (key === 'accent')  { values.primary    = value; continue; }
    if (key === 'accent2') { values.secondary  = value; continue; }
    values[key] = value;
  }

  const allowed = new Set(Object.keys(DEFAULT_PALETTE));
  for (const key of Object.keys(values)) {
    if (!allowed.has(key))
      throw new Error(`Unknown MQS palette key in ${sourceFile}: ${key}`);
  }

  return values;
}

/** Emit the full `:root { --mq-* }` block plus base component CSS. */
function buildEssentialsCSS(palette) {
  const p = palette;
  return `/* mqs-essentials: generated by marque */
:root {
  --mq-primary: ${p.primary};
  --mq-secondary: ${p.secondary};
  --mq-tertiary: ${p.tertiary};
  --mq-background: ${p.background};
  --mq-surface: ${p.surface};
  --mq-surface-alt: ${p['surface-alt']};
  --mq-text: ${p.text};
  --mq-muted: ${p.muted};
  --mq-border: ${p.border};
  --mq-nav-bg: ${p['nav-bg']};
  --mq-nav-text: ${p['nav-text']};
  --mq-nav-border: ${p['nav-border']};
  --mq-nav-active-bg: ${p['nav-active-bg']};
  --mq-nav-active-text: ${p['nav-active-text']};
  --mq-code-bg: ${p['code-bg']};
  --mq-code-text: ${p['code-text']};
  --mq-code-border: ${p['code-border']};
  --mq-code-head-bg: ${p['code-head-bg']};
  --mq-code-head-text: ${p['code-head-text']};
  --mq-code-copy-border: color-mix(in srgb, var(--mq-code-head-text) 35%, transparent);
  --mq-code-copy-bg: color-mix(in srgb, var(--mq-code-head-text) 8%, transparent);
  --mq-code-copy-bg-hover: color-mix(in srgb, var(--mq-code-head-text) 16%, transparent);
  --mq-card-bg: ${p['card-bg']};
  --mq-card-border: ${p['card-border']};
  --mq-card-shadow: ${p['card-shadow']};
  --mq-card-radius: ${p['card-radius']};
  --mq-callout-info-bg: ${p['callout-info-bg']};
  --mq-callout-info-border: ${p['callout-info-border']};
  --mq-callout-info-text: ${p['callout-info-text']};
  --mq-callout-warn-bg: ${p['callout-warn-bg']};
  --mq-callout-warn-border: ${p['callout-warn-border']};
  --mq-callout-warn-text: ${p['callout-warn-text']};
  --mq-callout-danger-bg: ${p['callout-danger-bg']};
  --mq-callout-danger-border: ${p['callout-danger-border']};
  --mq-callout-danger-text: ${p['callout-danger-text']};
  --mq-callout-ok-bg: ${p['callout-ok-bg']};
  --mq-callout-ok-border: ${p['callout-ok-border']};
  --mq-callout-ok-text: ${p['callout-ok-text']};
  --mq-radius: ${p.radius};
  --mq-max-width: ${p['max-width']};
  --mq-font-sans: ${p['font-sans']};
  --mq-font-serif: ${p['font-serif']};
  --mq-font-mono: ${p['font-mono']};

  /* compatibility aliases */
  --bg: var(--mq-background);
  --surface: var(--mq-surface);
  --surface2: var(--mq-surface-alt);
  --text: var(--mq-text);
  --muted: var(--mq-muted);
  --accent: var(--mq-primary);
  --accent2: var(--mq-secondary);
  --border: var(--mq-border);
  --radius: var(--mq-radius);
  --max-w: var(--mq-max-width);
  --font-sans: var(--mq-font-sans);
  --font-serif: var(--mq-font-serif);
  --font-mono: var(--mq-font-mono);
}

body {
  font-family: var(--mq-font-sans);
  background: var(--mq-background);
  color: var(--mq-text);
  font-size: 16px;
  line-height: 1.65;
}

.primary { --mq-tone: var(--mq-primary); }
.secondary { --mq-tone: var(--mq-secondary); }
.tertiary { --mq-tone: var(--mq-tertiary); }

.mq-nav { background: var(--mq-nav-bg); border-bottom: 1px solid var(--mq-nav-border); }
.mq-nav-brand { font-family: var(--mq-font-serif); font-size: 1.1rem; font-weight: 500; color: var(--mq-nav-text); text-decoration: none; letter-spacing: -0.02em; }

.mq-nav-links a,
.mq-nav-group > .mq-nav-group-trigger { font-size: 0.875rem; color: var(--mq-muted); text-decoration: none; border: 1px solid transparent; border-radius: 8px; transition: color 0.15s, border-color 0.15s, background 0.15s; }
.mq-nav-links a:hover,
.mq-nav-group > .mq-nav-group-trigger:hover { color: var(--mq-nav-active-text); border-color: var(--mq-nav-border); }
.mq-nav-links a.active,
.mq-nav-group > .mq-nav-group-trigger.active { color: var(--mq-nav-active-text); border-color: var(--mq-nav-border); background: var(--mq-nav-active-bg); }
.mq-nav-submenu { background: var(--mq-nav-bg); border: 1px solid var(--mq-nav-border); }

.mq-footer { font-size: 0.8rem; color: var(--mq-muted); border-top: 1px solid var(--mq-border); }
.mq-footer a { color: var(--mq-muted); }

.mq-main h1 { font-family: var(--mq-font-serif); font-size: clamp(1.8rem, 4vw, 2.6rem); font-weight: 500; letter-spacing: -0.03em; line-height: 1.15; margin-bottom: 1rem; }
.mq-main h2 { font-family: var(--mq-font-serif); font-size: 1.4rem; font-weight: 500; letter-spacing: -0.02em; margin-bottom: 0.5rem; line-height: 1.25; }
.mq-main h3 { font-family: var(--mq-font-sans); font-size: 1rem; font-weight: 500; margin-bottom: 0.4rem; }
.mq-main p { margin-bottom: 1rem; color: var(--mq-muted); font-size: 0.95rem; }
.mq-main a { color: var(--mq-secondary); text-decoration: none; }
.mq-main a:hover { text-decoration: underline; }
.mq-main hr { border: none; border-top: 1px solid var(--mq-border); margin: 2.5rem 0; }
.mq-main ul, .mq-main ol { padding-left: 1.5rem; margin-bottom: 1rem; color: var(--mq-muted); font-size: 0.95rem; }
.mq-main li { margin-bottom: 0.3rem; }
.mq-main code { font-family: var(--mq-font-mono); font-size: 0.84em; background: var(--mq-surface-alt); padding: 2px 6px; border-radius: 3px; }
.mq-main pre { background: var(--mq-code-bg); color: var(--mq-code-text); border: 1px solid var(--mq-code-border); padding: 1.25rem; border-radius: var(--mq-radius); overflow-x: auto; margin-bottom: 1rem; font-family: var(--mq-font-mono); font-size: 0.85rem; line-height: 1.7; }
.mq-main pre code { background: none; padding: 0; font-size: inherit; color: inherit; }
.mq-main blockquote { border-left: 3px solid var(--mq-primary); padding-left: 1rem; margin: 1rem 0; color: var(--mq-muted); font-style: italic; }
.mq-main strong { font-weight: 500; color: var(--mq-text); }

.mq-row { display: grid; gap: 1.25rem; margin: 1.75rem 0; align-items: stretch; }
.mq-column { display: grid; gap: 1.25rem; align-content: start; }
.mq-card { background: var(--mq-card-bg); border: 1px solid var(--mq-card-border); border-radius: var(--mq-card-radius); box-shadow: var(--mq-card-shadow); padding: 1.5rem; height: 100%; }
.mq-card.primary, .mq-card.accent   { border-top: 3px solid var(--mq-primary); }
.mq-card.secondary, .mq-card.accent2{ border-top: 3px solid var(--mq-secondary); }
.mq-card.tertiary { border-top: 3px solid var(--mq-tertiary); }
.mq-card.ghost   { background: transparent; }
.mq-card.dark    { background: var(--mq-text); border-color: transparent; }
.mq-card.dark h2, .mq-card.dark h3 { color: var(--mq-background); }
.mq-card.dark p  { color: rgba(247,245,240,0.6); }
.mq-card.dark .mq-btn { border-color: rgba(255,255,255,0.2); color: var(--mq-background); }

a.mq-btn { display: inline-block; margin-top: 0.75rem; padding: 0.45rem 1.1rem; border: 1px solid var(--mq-border); border-radius: 100px; font-size: 0.85rem; font-weight: 500; text-decoration: none !important; color: var(--mq-text); transition: background 0.15s; }
a.mq-btn:hover { background: var(--mq-surface-alt); }
a.mq-btn.primary { background: var(--mq-primary); border-color: var(--mq-primary); color: #fff; }
a.mq-btn.secondary, a.mq-btn.blue { background: var(--mq-secondary); border-color: var(--mq-secondary); color: #fff; }
a.mq-btn.tertiary { background: var(--mq-tertiary); border-color: var(--mq-tertiary); color: #fff; }
a.mq-btn.primary:hover, a.mq-btn.secondary:hover, a.mq-btn.blue:hover, a.mq-btn.tertiary:hover { filter: brightness(0.92); }

.mq-callout { padding: 1rem 1.25rem; border-radius: var(--mq-radius); margin: 0.75rem 0 1rem; border-left: 3px solid; }
.mq-callout p { margin: 0; }
.mq-callout > :first-child { margin-top: 0; }
.mq-callout > :last-child  { margin-bottom: 0; }
.mq-callout.info, .mq-callout.secondary { background: var(--mq-callout-info-bg); border-color: var(--mq-callout-info-border); }
.mq-callout.info p, .mq-callout.secondary p { color: var(--mq-callout-info-text); }
.mq-callout.warn, .mq-callout.primary { background: var(--mq-callout-warn-bg); border-color: var(--mq-callout-warn-border); }
.mq-callout.warn p, .mq-callout.primary p { color: var(--mq-callout-warn-text); }
.mq-callout.danger { background: var(--mq-callout-danger-bg); border-color: var(--mq-callout-danger-border); }
.mq-callout.danger p { color: var(--mq-callout-danger-text); }
.mq-callout.ok, .mq-callout.tertiary { background: var(--mq-callout-ok-bg); border-color: var(--mq-callout-ok-border); }
.mq-callout.ok p, .mq-callout.tertiary p { color: var(--mq-callout-ok-text); }

.mq-divider { width: 36px; height: 3px; background: var(--mq-primary); margin: 0.75rem 0 1rem; border-radius: 2px; }

.mq-stat { display: flex; flex-direction: column; gap: 0.3rem; padding: 1.25rem; background: var(--mq-surface); border: 1px solid var(--mq-border); border-radius: var(--mq-radius); }
.mq-stat-value { font-family: var(--mq-font-serif); font-size: 2.6rem; font-weight: 300; letter-spacing: -0.04em; line-height: 1; }
.mq-stat-label { font-size: 0.78rem; color: var(--mq-muted); text-transform: uppercase; letter-spacing: 0.08em; }

.mq-step { display: grid; grid-template-columns: 2rem 1fr; gap: 0.7rem; margin-bottom: 0.95rem; align-items: start; }
.mq-step-body > :first-child { margin-top: 0; }
.mq-step-body > :last-child  { margin-bottom: 0; }
.mq-step-num { width: 2rem; height: 2rem; border-radius: 50%; background: var(--mq-surface-alt); display: flex; align-items: center; justify-content: center; font-family: var(--mq-font-mono); font-size: 12px; font-weight: 500; flex-shrink: 0; color: var(--mq-muted); }
.mq-step-num::before { content: attr(data-step); }

.mq-spotlight, .mq-hero { padding: 2.2rem 1.3rem; margin: 0 0 2rem; border: 1px solid var(--mq-border); border-radius: var(--mq-radius); background: var(--mq-surface-alt); }
.mq-spotlight.center, .mq-hero.center { text-align: center; }

.mq-badge { display: inline-block; font-family: var(--mq-font-mono); font-size: 11px; padding: 2px 8px; border-radius: 100px; background: var(--mq-surface-alt); color: var(--mq-muted); letter-spacing: 0.03em; vertical-align: middle; }
.mq-badge.primary, .mq-badge.accent { background: #fdf0eb; color: var(--mq-primary); }
.mq-badge.secondary, .mq-badge.blue { background: #eef3fb; color: var(--mq-secondary); }
.mq-badge.tertiary { background: #eaf4ee; color: var(--mq-tertiary); }

@media (max-width: 640px) { .mq-row { grid-template-columns: 1fr !important; } }
`;
}

module.exports = { DEFAULT_PALETTE, parsePaletteBlock, buildEssentialsCSS };