const fs = require('fs');
const path = require('path');

const DEFAULT_PALETTE = {
  primary: '#c85a2a',
  secondary: '#2a5ac8',
  ternary: '#2ac852',
  background: '#f7f5f0',
  surface: '#ffffff',
  'surface-alt': '#eeece7',
  text: '#1a1916',
  muted: '#6b6860',
  border: 'rgba(0,0,0,0.09)',
  radius: '8px',
  'max-width': '860px',
  'font-sans': "'DM Sans', system-ui, sans-serif",
  'font-serif': "'Fraunces', Georgia, serif",
  'font-mono': "'IBM Plex Mono', monospace",
};

function compileMqs(source, options = {}) {
  const sourceFile = options.sourceFile || '<inline>';
  const rootDir = options.rootDir || path.dirname(sourceFile);
  const seen = options.seen || new Set();

  const realSource = safeRealpath(sourceFile);
  if (realSource && seen.has(realSource)) {
    throw new Error(`MQS circular import detected: ${sourceFile}`);
  }
  if (realSource) seen.add(realSource);

  const expandedImports = expandImports(String(source || '').replace(/^\uFEFF/, ''), {
    sourceFile,
    rootDir,
    seen,
  });

  const expandedDirectives = expandDirectives(expandedImports, sourceFile);

  if (realSource) seen.delete(realSource);
  return expandedDirectives;
}

function expandImports(source, options) {
  const { sourceFile, rootDir, seen } = options;
  const lines = source.split(/\r?\n/);
  const out = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const m = line.match(/^\s*@mqs-import\s+['\"]([^'\"]+)['\"]\s*;\s*$/);
    if (!m) {
      out.push(line);
      continue;
    }

    const rel = m[1].trim();
    const target = path.resolve(rootDir, rel);
    if (!fs.existsSync(target)) {
      throw new Error(`MQS import not found in ${sourceFile}:${i + 1} -> ${rel}`);
    }

    const importedSrc = fs.readFileSync(target, 'utf8');
      const importedCss = compileMqs(importedSrc, {
      sourceFile: target,
      rootDir: path.dirname(target),
      seen,
    });

    out.push(`/* mqs-import: ${rel} */`);
    out.push(importedCss);
    out.push(`/* end mqs-import: ${rel} */`);
  }

  return out.join('\n');
}

function expandDirectives(source, sourceFile) {
  let palette = { ...DEFAULT_PALETTE };
  let css = String(source || '');

  css = css.replace(/@mqs-palette\s*\{([\s\S]*?)\}\s*;?/gi, (_, block) => {
    palette = { ...palette, ...parsePaletteBlock(block, sourceFile) };
    return '';
  });

  css = css.replace(/@mqs-essentials\s*;/gi, () => buildEssentialsCSS(palette));
  return css;
}

function parsePaletteBlock(block, sourceFile) {
  const values = {};
  const cleaned = String(block || '')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/(^|\n)\s*\/\/.*(?=\n|$)/g, '$1');

  const pairRe = /([a-z][a-z0-9-]*)\s*:\s*([^;]+);?/gi;
  let match;
  while ((match = pairRe.exec(cleaned))) {
    const key = match[1].toLowerCase();
    const value = match[2].trim();
    if (!value) continue;
    if (key === 'bg') {
      values.background = value;
      continue;
    }
    if (key === 'accent') {
      values.primary = value;
      continue;
    }
    if (key === 'accent2') {
      values.secondary = value;
      continue;
    }
    values[key] = value;
  }

  const allowed = new Set(Object.keys(DEFAULT_PALETTE));
  for (const key of Object.keys(values)) {
    if (!allowed.has(key)) {
      throw new Error(`Unknown MQS palette key in ${sourceFile}: ${key}`);
    }
  }

  return values;
}

function buildEssentialsCSS(palette) {
  return `/* mqs-essentials: generated by marque */
:root {
  --mq-primary: ${palette.primary};
  --mq-secondary: ${palette.secondary};
  --mq-ternary: ${palette.ternary};
  --mq-background: ${palette.background};
  --mq-surface: ${palette.surface};
  --mq-surface-alt: ${palette['surface-alt']};
  --mq-text: ${palette.text};
  --mq-muted: ${palette.muted};
  --mq-border: ${palette.border};
  --mq-radius: ${palette.radius};
  --mq-max-width: ${palette['max-width']};
  --mq-font-sans: ${palette['font-sans']};
  --mq-font-serif: ${palette['font-serif']};
  --mq-font-mono: ${palette['font-mono']};

  /* compatibility aliases for existing themes/components */
  --bg: var(--mq-background);
  --surface: var(--mq-surface);
  --surface2: var(--mq-surface-alt);
  --text: var(--mq-text);
  --muted: var(--mq-muted);
  --accent: var(--mq-primary);
  --accent2: var(--mq-secondary);
  --border: var(--mq-border);
  --radius: var(--mq-radius);
  --max-w: var(--mq-max-width);
  --font-sans: var(--mq-font-sans);
  --font-serif: var(--mq-font-serif);
  --font-mono: var(--mq-font-mono);
}

body {
  font-family: var(--mq-font-sans);
  background: var(--mq-background);
  color: var(--mq-text);
  font-size: 16px;
  line-height: 1.65;
}

.primary { --mq-tone: var(--mq-primary); }
.secondary { --mq-tone: var(--mq-secondary); }
.ternary { --mq-tone: var(--mq-ternary); }

.mq-nav {
  background: var(--mq-surface);
  border-bottom: 1px solid var(--mq-border);
}

.mq-nav-brand {
  font-family: var(--mq-font-serif);
  font-size: 1.1rem;
  font-weight: 500;
  color: var(--mq-text);
  text-decoration: none;
  letter-spacing: -0.02em;
}

.mq-nav-links a,
.mq-nav-group > .mq-nav-group-trigger {
  font-size: 0.875rem;
  color: var(--mq-muted);
  text-decoration: none;
  border: 1px solid transparent;
  border-radius: 8px;
  transition: color 0.15s, border-color 0.15s, background 0.15s;
}

.mq-nav-links a:hover,
.mq-nav-group > .mq-nav-group-trigger:hover {
  color: var(--mq-text);
  border-color: var(--mq-border);
}

.mq-nav-links a.active,
.mq-nav-group > .mq-nav-group-trigger.active {
  color: var(--mq-text);
  border-color: color-mix(in srgb, var(--mq-primary) 55%, transparent);
  background: color-mix(in srgb, var(--mq-primary) 10%, transparent);
}

.mq-nav-submenu {
  background: var(--mq-surface);
  border: 1px solid var(--mq-border);
}

.mq-footer {
  font-size: 0.8rem;
  color: var(--mq-muted);
  border-top: 1px solid var(--mq-border);
}

.mq-footer a { color: var(--mq-muted); }

.mq-main h1 {
  font-family: var(--mq-font-serif);
  font-size: clamp(1.8rem, 4vw, 2.6rem);
  font-weight: 500;
  letter-spacing: -0.03em;
  line-height: 1.15;
  margin-bottom: 1rem;
}

.mq-main h2 {
  font-family: var(--mq-font-serif);
  font-size: 1.4rem;
  font-weight: 500;
  letter-spacing: -0.02em;
  margin-bottom: 0.5rem;
  line-height: 1.25;
}

.mq-main h3 {
  font-family: var(--mq-font-sans);
  font-size: 1rem;
  font-weight: 500;
  margin-bottom: 0.4rem;
}

.mq-main p { margin-bottom: 1rem; color: var(--mq-muted); font-size: 0.95rem; }
.mq-main a { color: var(--mq-secondary); text-decoration: none; }
.mq-main a:hover { text-decoration: underline; }
.mq-main hr { border: none; border-top: 1px solid var(--mq-border); margin: 2.5rem 0; }
.mq-main ul, .mq-main ol { padding-left: 1.5rem; margin-bottom: 1rem; color: var(--mq-muted); font-size: 0.95rem; }
.mq-main li { margin-bottom: 0.3rem; }
.mq-main code { font-family: var(--mq-font-mono); font-size: 0.84em; background: var(--mq-surface-alt); padding: 2px 6px; border-radius: 3px; }
.mq-main pre { background: #1e1c18; color: #e8e4dc; padding: 1.25rem; border-radius: var(--mq-radius); overflow-x: auto; margin-bottom: 1rem; font-family: var(--mq-font-mono); font-size: 0.85rem; line-height: 1.7; }
.mq-main pre code { background: none; padding: 0; font-size: inherit; color: inherit; }
.mq-main blockquote { border-left: 3px solid var(--mq-primary); padding-left: 1rem; margin: 1rem 0; color: var(--mq-muted); font-style: italic; }
.mq-main strong { font-weight: 500; color: var(--mq-text); }

.mq-row {
  display: grid;
  gap: 1.25rem;
  margin: 1.75rem 0;
  align-items: stretch;
}

.mq-card {
  background: var(--mq-surface);
  border: 1px solid var(--mq-border);
  border-radius: calc(var(--mq-radius) + 2px);
  padding: 1.5rem;
  height: 100%;
}

.mq-card.primary,
.mq-card.accent { border-top: 3px solid var(--mq-primary); }

.mq-card.secondary,
.mq-card.accent2 { border-top: 3px solid var(--mq-secondary); }

.mq-card.ternary { border-top: 3px solid var(--mq-ternary); }
.mq-card.ghost { background: transparent; }
.mq-card.dark { background: var(--mq-text); border-color: transparent; }
.mq-card.dark h2,
.mq-card.dark h3 { color: var(--mq-background); }
.mq-card.dark p { color: rgba(247,245,240,0.6); }
.mq-card.dark .mq-btn { border-color: rgba(255,255,255,0.2); color: var(--mq-background); }

a.mq-btn {
  display: inline-block;
  margin-top: 0.75rem;
  padding: 0.45rem 1.1rem;
  border: 1px solid var(--mq-border);
  border-radius: 100px;
  font-size: 0.85rem;
  font-weight: 500;
  text-decoration: none !important;
  color: var(--mq-text);
  transition: background 0.15s;
}

a.mq-btn:hover { background: var(--mq-surface-alt); }
a.mq-btn.primary { background: var(--mq-primary); border-color: var(--mq-primary); color: #fff; }
a.mq-btn.secondary,
a.mq-btn.blue { background: var(--mq-secondary); border-color: var(--mq-secondary); color: #fff; }
a.mq-btn.ternary { background: var(--mq-ternary); border-color: var(--mq-ternary); color: #fff; }
a.mq-btn.primary:hover,
a.mq-btn.secondary:hover,
a.mq-btn.blue:hover,
a.mq-btn.ternary:hover { filter: brightness(0.92); }

.mq-callout {
  padding: 1rem 1.25rem;
  border-radius: var(--mq-radius);
  margin: 0.75rem 0 1rem;
  border-left: 3px solid;
}

.mq-callout p { margin: 0; }
.mq-callout > :first-child { margin-top: 0; }
.mq-callout > :last-child { margin-bottom: 0; }
.mq-callout.info,
.mq-callout.secondary { background: #eef3fb; border-color: var(--mq-secondary); }
.mq-callout.info p,
.mq-callout.secondary p { color: #1a3060; }
.mq-callout.warn,
.mq-callout.primary { background: #fdf5e8; border-color: var(--mq-primary); }
.mq-callout.warn p,
.mq-callout.primary p { color: #5a3510; }
.mq-callout.danger { background: #fbeaea; border-color: #c82a2a; }
.mq-callout.danger p { color: #5a1010; }
.mq-callout.ok,
.mq-callout.ternary { background: #eaf4ee; border-color: var(--mq-ternary); }
.mq-callout.ok p,
.mq-callout.ternary p { color: #0e4020; }

.mq-divider {
  width: 36px;
  height: 3px;
  background: var(--mq-primary);
  margin: 0.75rem 0 1rem;
  border-radius: 2px;
}

.mq-stat {
  display: flex;
  flex-direction: column;
  gap: 0.3rem;
  padding: 1.25rem;
  background: var(--mq-surface);
  border: 1px solid var(--mq-border);
  border-radius: var(--mq-radius);
}

.mq-stat-value {
  font-family: var(--mq-font-serif);
  font-size: 2.6rem;
  font-weight: 300;
  letter-spacing: -0.04em;
  line-height: 1;
}

.mq-stat-label {
  font-size: 0.78rem;
  color: var(--mq-muted);
  text-transform: uppercase;
  letter-spacing: 0.08em;
}

.mq-tabs { margin: 1.5rem 0; }
.mq-tab-bar { display: flex; border-bottom: 1px solid var(--mq-border); margin-bottom: 0; }
.mq-tab-btn {
  padding: 0.5rem 1.1rem;
  border: none;
  background: none;
  cursor: pointer;
  font-family: var(--mq-font-sans);
  font-size: 0.875rem;
  color: var(--mq-muted);
  border-bottom: 2px solid transparent;
  margin-bottom: -1px;
  transition: color 0.15s;
}

.mq-tab-btn:hover { color: var(--mq-text); }
.mq-tab-btn.active { color: var(--mq-text); border-bottom-color: var(--mq-primary); font-weight: 500; }
.mq-tab-content { display: none; padding: 1.25rem 0; }
.mq-tab-content.active { display: block; }

.mq-steps { margin: 1.5rem 0; counter-reset: mq-steps; }
.mq-step {
  display: grid;
  grid-template-columns: 2rem 1fr;
  gap: 0.7rem;
  margin-bottom: 0.95rem;
  align-items: start;
}

.mq-step-body > :first-child { margin-top: 0; }
.mq-step-body > :last-child { margin-bottom: 0; }

.mq-step-num {
  counter-increment: mq-steps;
  content: counter(mq-steps);
  width: 2rem;
  height: 2rem;
  border-radius: 50%;
  background: var(--mq-surface-alt);
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: var(--mq-font-mono);
  font-size: 12px;
  font-weight: 500;
  flex-shrink: 0;
  color: var(--mq-muted);
}

.mq-step-num::before { content: counter(mq-steps); }

.mq-hero {
  padding: 4rem 0 3rem;
  margin-bottom: 2rem;
}

.mq-hero.center { text-align: center; }

.mq-badge {
  display: inline-block;
  font-family: var(--mq-font-mono);
  font-size: 11px;
  padding: 2px 8px;
  border-radius: 100px;
  background: var(--mq-surface-alt);
  color: var(--mq-muted);
  letter-spacing: 0.03em;
  vertical-align: middle;
}

.mq-badge.primary,
.mq-badge.accent { background: #fdf0eb; color: var(--mq-primary); }
.mq-badge.secondary,
.mq-badge.blue { background: #eef3fb; color: var(--mq-secondary); }
.mq-badge.ternary { background: #eaf4ee; color: var(--mq-ternary); }

@media (max-width: 640px) {
  .mq-row { grid-template-columns: 1fr !important; }
}
`;
}

function safeRealpath(filePath) {
  try {
    return fs.realpathSync(filePath);
  } catch (_) {
    return null;
  }
}

function compileMqsFile(filePath) {
  const source = fs.readFileSync(filePath, 'utf8');
  return compileMqs(source, {
    sourceFile: filePath,
    rootDir: path.dirname(filePath),
    seen: new Set(),
  });
}

module.exports = {
  compileMqs,
  compileMqsFile,
};
